

spring:
  application:
    name: agent-java

  datasource:
    driver-class-name: YourDriverClassName
    url: YourURL
    username: YourUsername
    password: YourPassword
  cloud:
    nacos:
      server-addr: YourNacosServerAddr
    openfeign:
      client:
        config:
          ai-agent-service:
            loggerLevel: FULL
logging:
  level:
    com.agent.feign: DEBUG
    com.alibaba.nacos: WARN

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.agent.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081
